name: opcua-commander 
base: core22
version: "0.39.0"
title: OPC UA Commander
contact: https://github.com/node-opcua/opcua-commander/issues
license: MIT
issues: https://github.com/node-opcua/opcua-commander/issues
source-code: https://github.com/node-opcua/opcua-commander
website: https://sterfive.com
summary: Curse based OPCUA Client for the command line
description: |
  opcua-commander is a OPCUA Client application that runs in the terminal.
  It's based on ncurse and NodeOPCUA.
  author: Etienne Rossignon - Sterfive SAS

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
parts:
  opcua-commander:
    # See 'snapcraft plugins'
    plugin: npm
    npm-include-node: true
    npm-node-version: "22.11.0"
    # plugin: nodejs
    # nodejs-package-manager: npm
    # nodejs-version: "22.11.0"
    source: . 
    stage-packages:
      - openssl

apps:
  opcua-commander:
    command: bin/opcua-commander.js
    plugs:
      - network
    environment:
      OPENSSL_CONF: /dev/null
